# This file is generated by gyp; do not edit.

export builddir_name ?= /work/chrome_base.git/src/base/allocator/out
.PHONY: all
all:
	$(MAKE) -C ../.. allocator_extension_thunks allocator_extension_thunks allocator
