# This file is generated by gyp; do not edit.

export builddir_name ?= /work/chrome_base.git/src/base/out
.PHONY: all
all:
	$(MAKE) -C .. xdg_mime symbolize xdg_mime symbolize base_static base_static base base check_example test_support_perf base_prefs base_i18n test_support_base base_prefs_test_support run_all_unittests base_unittests
